# Global Settings
global:
  environment: production
  registry: localhost:5000

# Persistent Volume Settings
persistentVolumes:
  # Set to true to use existing PVs instead of creating new ones
  # This allows preserving data when transitioning to Helm
  useExisting: false

# Frontend Configuration
frontend:
  replicaCount: 1
  image:
    repository: frontend
    tag: latest
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  probes:
    readiness:
      initialDelaySeconds: 10
      periodSeconds: 30
  # API configuration
  api:
    # Set to "internal" for cluster DNS, "external" to use ingress URL
    mode: "internal"
    # When using internal mode, use the k8s service name
    internalUrl: "http://backend-service:8080"
    # When using external mode, use the ingress URL
    externalUrl: "https://madevara24.space/api"

# Backend Configuration
backend:
  replicaCount: 1
  image:
    repository: backend-service
    tag: latest
  port: 8080
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  probes:
    readiness:
      path: /health
      initialDelaySeconds: 5
      periodSeconds: 10
    liveness:
      path: /health
      initialDelaySeconds: 15
      periodSeconds: 20

# PostgreSQL Configuration
postgres:
  image:
    repository: postgres-vector
    tag: latest
  config:
    maxConnections: 100
    sharedBuffers: 128MB
    effectiveCacheSize: 384MB
  storage:
    size: 10Gi
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

# Logging Configuration
logging:
  grafana:
    enabled: true
    storage:
      size: 2Gi
  loki:
    enabled: true
    storage:
      size: 5Gi
    retention:
      days: 30
  promtail:
    enabled: true
    positions:
      storage:
        size: 1Gi

# Ingress Configuration
ingress:
  enabled: true
  className: traefik
  domain: madevara24.space
  paths:
    frontend: /
    backend: /backend
  tls:
    enabled: true
    # Secret must be created manually before deploying:
    # kubectl create secret tls madevara24-tls --cert=/path/to/cert.pem --key=/path/to/key.pem
    secretName: madevara24-tls 