apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    {{- include "monorepo-display-case.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    app: backend-service
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  type: {{ .Values.backend.service.type | default "ClusterIP" }} 