apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "monorepo-display-case.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: {{ .Values.frontend.service.type | default "ClusterIP" }} 