{{- if .Values.logging.loki.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  labels:
    {{- include "monorepo-display-case.labels" . | nindent 4 }}
    app.kubernetes.io/component: logging
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    limits_config:
      retention_period: {{ .Values.logging.loki.retention.days }}d      # Keep logs for specified days
      max_entries_limit_per_query: 5000
      reject_old_samples: true
      reject_old_samples_max_age: 168h  # 7 days
      allow_structured_metadata: false  # Disable structured metadata for compatibility

    table_manager:
      retention_deletes_enabled: true
      retention_period: {{ mul .Values.logging.loki.retention.days 24 }}h     # Convert days to hours

    compactor:
      working_directory: /loki/compactor
      compaction_interval: 10m
      retention_enabled: true
      delete_request_store: filesystem

    schema_config:
      configs:
        - from: 2020-05-15
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
{{- end }}
{{- if .Values.logging.promtail.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  labels:
    {{- include "monorepo-display-case.labels" . | nindent 4 }}
    app.kubernetes.io/component: logging
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /positions/positions.yaml
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_controller_name
            regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
            target_label: __service__
          - source_labels:
              - __meta_kubernetes_pod_node_name
            target_label: node_name
          - source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
{{- end }} 