{{- if .Values.logging.loki.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    {{- include "monorepo-display-case.labels" . | nindent 4 }}
    app.kubernetes.io/component: logging
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
  type: ClusterIP
{{- end }}
{{- if .Values.logging.grafana.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    {{- include "monorepo-display-case.labels" . | nindent 4 }}
    app.kubernetes.io/component: logging
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
{{- end }} 