apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Note: These values should be base64 encoded
  POSTGRES_USER: cG9zdGdyZXM=      # 'postgres' in base64
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # 'password' in base64
  POSTGRES_DB: ZGlzcGxheWNhc2U=   # 'displaycase' in base64 