apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Note: These values should be base64 encoded
  POSTGRES_USER: ZXRtaW4=
  POSTGRES_PASSWORD: c3VkYWhkYXRhbmc=
  POSTGRES_DB: bW9ub3JlcG8tZGlzcGxheS1jYXNl